version: 0.2
env:
  variables:
    PROJECT_NAME: "standard-manager-api"
    REGION: "sa-east-1"
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing all requirements
      - pip install -r ./requirements.txt
      - pip install -r ./requirements-vendor.txt
  build:
    commands:
      - echo Bulding docker image
      - ./bin/aws/ecr-docker-build.sh
      - echo Generating docker tag
      - ./bin/aws/ecr-docker-tag.sh $ACCOUNT_ID
  post_build:
    commands:
      - echo Loging in ECR
      - PASSWORD=$(aws ecr get-login-password --region sa-east-1)
      - docker login -u AWS -p $PASSWORD $ACCOUNT_ID.dkr.ecr.sa-east-1.amazonaws.com
      - echo Pushing docker images
      - ./bin/aws/ecr-docker-push.sh $ACCOUNT_ID
    #      - echo Installing test requirements
    #      - pip install -r ./requirements-tests.txt
    #      - echo Running unit testes
    #      - ./bin/tests/unit-coverage-no-report-html.sh
    finally:
      - echo Generating imagedefinitions.json file
      - printf '[{"name":"%s", "imageUri":"%s"}]' "${PROJECT_NAME}" "${ACCOUNT_ID}.dkr.ecr.sa-east-1.amazonaws.com/${PROJECT_NAME}" >> imagedefinitions.json
      - cat imagedefinitions.json
#      - echo Generating package file
#      - ./bin/tools/package.sh
#reports:
#  UnitTestsReports:
#    files:
#      - 'target/unit/clover.xml'
#    file-format: 'CLOVERXML'
artifacts:
  files:
    - imagedefinitions.json