# Generated by Django 3.1.5 on 2021-01-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('identification', models.CharField(max_length=100)),
                ('publication_date', models.DateField()),
                ('validity_start', models.DateField()),
                ('title', models.CharField(default='', max_length=100)),
                ('title_global_language', models.CharField(default='', max_length=100)),
                ('comite', models.CharField(default='', max_length=100)),
                ('pages', models.IntegerField()),
                ('status', models.CharField(choices=[('Arquivado', 'Arquivado'), ('Em Vigor', 'Em Vigor')], default=('Arquivado', 'Arquivado'), max_length=100)),
                ('language', models.CharField(choices=[('Inglês', 'Inglês'), ('Português', 'Português')], default=('Inglês', 'Inglês'), max_length=50)),
                ('organization', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('currency', models.CharField(choices=[('BRL', 'BRL'), ('EUR', 'EUR'), ('USD', 'USD')], default=('BRL', 'BRL'), max_length=5)),
                ('objective', models.TextField()),
                ('url', models.URLField()),
                ('file', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'organization'],
            },
        ),
    ]
