# Generated by Django 3.1.5 on 2021-01-17 05:23

from django.db import migrations
import rest_api.v1.models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='standard',
            managers=[
                ('objects', rest_api.v1.models.StandardManager()),
            ],
        ),
    ]
