# Generated by Django 3.1.5 on 2021-01-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_auto_20210117_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='standard',
            name='objective',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='standard',
            name='pages',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='standard',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='standard',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
