# Generated by Django 3.1.5 on 2021-01-18 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_auto_20210118_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='objective',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='standard',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
