# Generated by Django 3.1.5 on 2021-01-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_auto_20210118_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='currency',
            field=models.CharField(choices=[('BRL',), ('EUR',), ('USD',)], default=('BRL',), max_length=5),
        ),
        migrations.AlterField(
            model_name='standard',
            name='language',
            field=models.CharField(choices=[('Inglês',), ('Português',)], default=('Inglês',), max_length=50),
        ),
        migrations.AlterField(
            model_name='standard',
            name='status',
            field=models.CharField(choices=[('Arquivado',), ('Em Vigor',)], default=('Arquivado',), max_length=100),
        ),
    ]
