# Generated by Django 3.1.5 on 2021-01-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_auto_20210118_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='currency',
            field=models.CharField(choices=[('B', 'R', 'L'), ('E', 'U', 'R'), ('U', 'S', 'D')], default=('B', 'R', 'L'), max_length=5),
        ),
        migrations.AlterField(
            model_name='standard',
            name='language',
            field=models.CharField(choices=[('I', 'n', 'g', 'l', 'ê', 's'), ('P', 'o', 'r', 't', 'u', 'g', 'u', 'ê', 's')], default=('I', 'n', 'g', 'l', 'ê', 's'), max_length=50),
        ),
        migrations.AlterField(
            model_name='standard',
            name='status',
            field=models.CharField(choices=[('A', 'r', 'q', 'u', 'i', 'v', 'a', 'd', 'o'), ('E', 'm', ' ', 'V', 'i', 'g', 'o', 'r')], default=('A', 'r', 'q', 'u', 'i', 'v', 'a', 'd', 'o'), max_length=100),
        ),
    ]
