# Generated by Django 3.1.5 on 2021-01-18 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0007_auto_20210118_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='currency',
            field=models.CharField(choices=['Real', 'Dollar', 'Euro'], default='Real', max_length=5),
        ),
        migrations.AlterField(
            model_name='standard',
            name='file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='standard',
            name='language',
            field=models.CharField(choices=['Português', 'English'], default='Português', max_length=50),
        ),
        migrations.AlterField(
            model_name='standard',
            name='objective',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='standard',
            name='status',
            field=models.CharField(choices=['Em Vigor', 'Arquivado'], default='Em Vigor', max_length=100),
        ),
    ]
