components:
  schemas:
    Link:
      properties:
        href:
          type: string
        method:
          type: string
        rel:
          type: string
      type: object
    Meta:
      properties:
        first:
          format: url
          type: string
        href:
          format: url
          type: string
        last:
          format: url
          type: string
        next:
          format: url
          type: string
        previous:
          format: url
          type: string
      type: object
    PingSchema:
      properties:
        message:
          type: string
      type: object
    RequestControl:
      properties:
        count:
          type: integer
        limit:
          type: integer
        offset:
          type: integer
        total:
          type: integer
      required:
      - limit
      type: object
    Standard:
      properties:
        comite:
          type: string
        currency:
          type: string
        file:
          type: string
        identification:
          type: string
        language:
          type: string
        objective:
          type: string
        organization:
          type: string
        pages:
          type: integer
        price:
          type: number
        publication_date:
          format: date
          type: string
        status:
          type: string
        title:
          type: string
        title_global_language:
          type: string
        url:
          format: url
          type: string
        uuid:
          format: uuid
          type: string
        validity_start:
          format: date
          type: string
      type: object
    StandardList:
      properties:
        control:
          $ref: '#/components/schemas/RequestControl'
        data:
          items:
            $ref: '#/components/schemas/Standard'
          type: array
        links:
          items:
            $ref: '#/components/schemas/Link'
          type: array
        meta:
          $ref: '#/components/schemas/Meta'
      type: object
info:
  title: standard-manager-api
  version: 1.0.0
openapi: 3.0.2
paths:
  /ping:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PingSchema'
          description: Success response
      summary: PING method
  /v1/standard:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardList'
          description: Success response
      summary: List all standards
